name: Tweet Slang Bot

on:
  workflow_dispatch: # 手動実行を許可
  schedule:
    # JST (UTC+9) での実行スケジュール
    # 7:00 JST = 22:00 UTC (前日)
    # 12:00 JST = 3:00 UTC
    # 17:00 JST = 8:00 UTC
    # 18:00 JST = 9:00 UTC
    # 19:00 JST = 10:00 UTC
    # 20:00 JST = 11:00 UTC
    - cron: '0 22 * * *'
    - cron: '0 3 * * *'
    - cron: '0 8 * * *'
    - cron: '0 9 * * *'
    - cron: '0 10 * * *'
    - cron: '0 11 * * *'

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # プロジェクトに合わせたバージョンを指定

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run script
        run: python x.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }} 